# This is a basic workflow to help you get started with Actions

name: deploy-cms

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3.1.0
        with: 
          node-version: "14"
      - name: install pnpm
        uses: pnpm/action-setup@v2.2.1
      - name: install deps
        run: pnpm install
      - name: env
        run:
          export ECRET=${{secrets.ECRET}}
          export API_TOKEN_SALT=${{secrets.API_TOKEN_SALT}}
          export DATABASE_HOST=${{secrets.DATABASE_HOST}}
          export DATABASE_PORT=${{secrets.DATABASE_PORT}}
          export DATABASE_NAME=${{secrets.DATABASE_NAME}}
          export DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}}
          export DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}}
          export JWT_SECRET=${{secrets.JWT_SECRET}}
      - name: build
        run: pnpm build
      - name: deploy
        uses: appleboy/scp-action@master
        with: 
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USER}}
          password: ${{secrets.SERVER_PASSWORD}}
          port: 22
          source: "build/"
          target: ${{secrets.SERVER_TARGET}}
        

